### ISSUE TITLE
Карта: непонятная точка с координатой 0-0

### ISSUE THREAD

**Issue by gormxm** [infographer/ironviz#1]
Исправить точку в левом верхнем углу - старт "Кентинг" (Тайвань)

**Comment by TatyanaSkorochkina** [comment]
![2015-10-28 13-02-16 tri infographer ru starts](https://cloud.githubusercontent.com/assets/15325322/10785249/c0ec96fc-7d73-11e5-98b5-2d6c59fa6f8c.png)

**Comment by TatyanaSkorochkina** [comment]
ОК
