### ISSUE TITLE
Город проживания - Россия

### ISSUE THREAD

**Issue by TatyanaSkorochkina** [infographer/ironviz#12]
Актуализировать города, откуда приехали атлеты; исключить на карте точку "Россия"

**Comment by jajapr** [comment]
Татьяна, прикрепите, пожалуйста, к задаче актуальную версию таблицы, где указаны все города, откуда приехали атлеты. В этом случае, Россия, как точка видна не будет.

**Comment by TatyanaSkorochkina** [comment]
Майя, пока такой таблицы нет и высока вероятность того, что какие-то прошлые данные найти уже не удастся. Можем мы не выводить на карту точку, если для неё не задан город?? Так как таких данных немного, то визуально это не должно как-то бросаться в глаза...

**Comment by priezz** [comment]
Ок, давайте будем игнорировать точки, для которых не указан город

1 декабря 2015 г., 21:47 пользователь TatyanaSkorochkina <
notifications@github.com> написал:
