### ISSUE TITLE
Среднее время

### ISSUE THREAD

**Issue by TatyanaSkorochkina** [infographer/ironviz#13]
Исправить в результатах значение среднего времени: в поп-апе и на шкале разные значения

**Comment by TatyanaSkorochkina** [comment]
![2015-10-28 12-33-56 tri infographer ru distribiution age](https://cloud.githubusercontent.com/assets/15325322/10784530/b9788f88-7d6f-11e5-8118-fbddd748b650.png)

**Comment by TatyanaSkorochkina** [comment]
@priezz  @jajapr  сейчас новая проблема - теперь некорректно отображается поп-ап со средним временем для диапазонов 18-24; 30-34; 40-44 и 50-54
![2015-12-13 01-14-26 tri infographer ru distribiution age](https://cloud.githubusercontent.com/assets/15325322/11764185/2fe470d4-a137-11e5-952b-06c093fdf213.png)
![2015-12-13 01-17-28 tri infographer ru distribiution age](https://cloud.githubusercontent.com/assets/15325322/11764186/2feb3856-a137-11e5-980c-f5aa1f1027cd.png)

**Comment by TatyanaSkorochkina** [comment]
И еще один момент - всё-таки чтобы получить одинаковое значение в окошке и на шкале нужно очень постараться )) В противном случае всё равно небольшое расхождение возникает, что сбивает с толку. 
Может быть стоит оставить только ползунок, пересекающий ось времени, но не выводить на нём значение, зависимое от положения курсора? 
Либо в идеале, если это не слишком сложно технически, отображать ползунок не в привязке к курсору, а в привязке к конкретной временной точке, которую пользователь хочет посмотреть.

**Comment by TatyanaSkorochkina** [comment]
И ещё один момент - чтобы время в поп-апе и на оси совпало, нужно очень постараться ))
В противном случае небольшое расхождение всё равно есть, что сбивает с толку.
Может быть оставить только ползунок, а значение времени, завязаное на положение курсора, не выводить?
Либо в идеале, если это не слишком сложно технически, выводить ползунок со значением времени на оси не в привязке к положению курсора, а в привязке к конкретной точке с данными, которую пользователь выбрал (ползунок пустить ровно через центр точки)?

**Comment by priezz** [comment]
"некорректно отображается поп-ап со средним временем для диапазонов 18-24; 30-34; 40-44 и 50-54" - не вполне ясно, в чем именно заключается некорректность. И как должно быть корректно.  Из скриншотов это не видно. Также не ясно, что именно обведено красным.

Время в попапе и на оси никак не связаны. Значение на оси соответствует точной позиции курсока мыши, а значение к попапу - это конкретный результат, который никак не зависит от того, в каком месте кружка или иконки часов курсор в данный момент. Окрестность каждого результата зависит от разрешения монитора, в моем случае это около 10 минут.

В любом случае все комментарии относятся не к исправлению данного бага со средним временем, который исправлен, а к issue #14, прошу перенести обсуждение туда.

**Comment by TatyanaSkorochkina** [comment]
@priezz Александр, не считаю, что это относится к #14. Это несколько другая проблема - создаю для неё новую задачу. 
Эту задачу считаем закрытой.
