### ISSUE TITLE
Расхождение значений

### ISSUE THREAD

**Issue by TatyanaSkorochkina** [infographer/ironviz#14]
По конкретной точке не соответствует время на шкале и в результатах участника в поп-апе

**Comment by TatyanaSkorochkina** [comment]
![2015-10-28 12-36-25 tri infographer ru distribiution age](https://cloud.githubusercontent.com/assets/15325322/10784589/1591f0a2-7d70-11e5-98f4-5d599af55eb6.png)

**Comment by priezz** [comment]
Время внизу соответствует не выбранному результату, а позиции курсора мыши. Так и должо быть.

**Comment by TatyanaSkorochkina** [comment]
@priezz  @jajapr  Давайте здесь реализуем один из вариантов, которые я предложила для задачи 13

**Comment by priezz** [comment]
На наш взгляд, менять значение шкалы на значение ближайшего попапа неправильно. Это два разных индикатора, выводящих разную информацию. Зачем эту информацию дублировать? Техническую же возможность это сделать надо изучать отдельно.  Совсем выключить индикатор на шкале скорее всего можно.

**Comment by priezz** [comment]
Выключили отображение текущего значения курсора
