### ISSUE TITLE
Ось времени

### ISSUE THREAD

**Issue by TatyanaSkorochkina** [infographer/ironviz#16]
В разделе Результаты время внизу не должно меняться при переключении по возрастным группам - единый минимум и максимум

**Comment by TatyanaSkorochkina** [comment]
@priezz  @jajapr  изменений не увидела.. Проверьте, пожалуйста

**Comment by priezz** [comment]
Мы об одном и том же говорим? Измениния вносили в график "Распределение по возрастам". Теперь независимо от настроек фильтров, шкала всегда с 7:00 до 20:30

**Comment by priezz** [comment]
![distrib_age](https://cloud.githubusercontent.com/assets/6680317/11790020/f041a8fc-a299-11e5-927d-2fd2cd4b0130.png)

**Comment by TatyanaSkorochkina** [comment]
То, что сделали, тоже нужно. Но я имела в виду оба раздела в Результатах, и как раз в первую очередь раздел Анализ по возрастам, так как только там есть возможность фильтрации по возрастным группам. И сейчас при переключении шкала меняется, отражая минимальное и максимальное значение для конкретной группы, а мы хотели, чтобы минимум и максимум на шкале был зафиксирован общий для всех групп
![2015-12-15 14-05-43 tri infographer ru analysis age](https://cloud.githubusercontent.com/assets/15325322/11808945/a1e1f838-a334-11e5-9cf5-f02b22f11b91.png)
![2015-12-15 14-07-03 tri infographer ru analysis age](https://cloud.githubusercontent.com/assets/15325322/11808944/a1dead40-a334-11e5-8570-337e7854bdd7.png)
