### ISSUE TITLE
Список атлетов

### ISSUE THREAD

**Issue by TatyanaSkorochkina** [infographer/ironviz#17]
Добавить кол-во финишей для каждого атлета (будет обновленный макет от Олега)

**Comment by TatyanaSkorochkina** [comment]
@priezz  @jajapr  Давайте заменим заголовок "Количество стартов (всего)" на "Количество финишей"

**Comment by priezz** [comment]
Надо как-то показать, что это кол-во финифей именно за все годы.

**Comment by priezz** [comment]
Да  и правильно ли говорить о финишах? Насколько я помню, среди данных были в т.ч. без плавания и без чего-то еще.

**Comment by TatyanaSkorochkina** [comment]
@maxgorbachevskiy @priezz  Может быть назовём тогда этот столбец "Всего пройдено дистанций"? Или "Общее количество дистанций"?

**Comment by priezz** [comment]
Поменяли на "Всего пройдено дистанций"
