### ISSUE TITLE
Отображение поп-апов (результаты)

### ISSUE THREAD

**Issue by TatyanaSkorochkina** [infographer/ironviz#19]
При отображении поп-апа периодически закрывается сама точка

**Comment by TatyanaSkorochkina** [comment]
![2015-10-28 12-16-18 dropbox - screenshot 2015-10-23 18 06 16 png](https://cloud.githubusercontent.com/assets/15325322/10784224/f1cd6f68-7d6d-11e5-913d-c617c98015a0.png)

**Comment by priezz** [comment]
С этим ничего нельзя сделать. Поведение обусловлено библиотекой AmCharts.
