### ISSUE TITLE
Дублирование номеров

### ISSUE THREAD

**Issue by TatyanaSkorochkina** [infographer/ironviz#21]
Актуализировать номера атлетов: 
3
4
8
12
20
24
28
36
40
44
48
56
72
80
88
104
112

**Comment by TatyanaSkorochkina** [comment]
![2015-10-28 14-31-50 tri infographer ru list](https://cloud.githubusercontent.com/assets/15325322/10787235/438c549c-7d80-11e5-8fa0-e6736317d308.png)

**Comment by jajapr** [comment]
Есть ли какая-то возможность узнать ФИО и старты для следующих номеров от TRILIFE  (в последней таблице данные номера отсутствуют)?
388
389
390
391
392
393
394
396
397
398
399
401
402
404
405
409
410
412
537

**Comment by TatyanaSkorochkina** [comment]
@jajapr Майя, прикладываю актуальную табличку.

**Comment by priezz** [comment]
@TatyanaSkorochkina таблички во вложении нет...

**Comment by TatyanaSkorochkina** [comment]
ОК
