### ISSUE TITLE
Обратная связь

### ISSUE THREAD

**Issue by TatyanaSkorochkina** [infographer/ironviz#26]
На каждый поп-ап с информацией добавить текст «информация неполная»? - напиши на info@trilife.ru

**Comment by jajapr** [comment]
Предлагаем перенести в 1.0

**Comment by TatyanaSkorochkina** [comment]
@jajapr ОК, давайте перенесём. Сейчас жду от Трилайфа подтверждения электронки для обратной связи.

**Comment by TatyanaSkorochkina** [comment]
@jajapr адрес для обратной связи - contact@trilife.ru; можно делать )

**Comment by TatyanaSkorochkina** [comment]
Ждём от Олега решения по дизайну

**Comment by TatyanaSkorochkina** [comment]
Давайте поменяем оформление "обратной связи" следующим образом:

![002_portrait](https://cloud.githubusercontent.com/assets/15325322/11965461/b1fd9f8e-a905-11e5-9a80-e54378f3a1f5.png)
