### ISSUE TITLE
Цифра на главной странице

### ISSUE THREAD

**Issue by TatyanaSkorochkina** [infographer/ironviz#3]
Пред-кэшировать цифру на главной странице (она сначала = 0, а потом после общей дозагрузки уже показывает реальное значение)

**Comment by TatyanaSkorochkina** [comment]
@priezz  @jajapr  Сейчас сначала выводится цифра 500+, потом через несколько секунд реальное значение 747

**Comment by priezz** [comment]
Верно. А что вы предлагаете выводить? Программа же не знает, столько человек, пока не подгрузит данные по ним и не посчитает. Поэтому сначала выводится заглушка, которая потом заменяется реальным значением.

**Comment by priezz** [comment]
Можно до получения данных вообще ничего не выводить (например крутить колесо на заблюреном фоне), но нам кажется, что это будет раздражать пользователей несколько более, чем "более 500". Ну а текс может быть любым "Более 700", "700+", "Скоро 1000" и т.п.

**Comment by priezz** [comment]
Можно вместо числа (текста) показывать какую-то анимированную гифку, отображающую процесс загрузки (колесо велосипеда или что угодно еще, соответствующее тематике)

**Comment by priezz** [comment]
Задачу закрываем или меняем временный текст на другой?

**Comment by TatyanaSkorochkina** [comment]
@priezz Максим предложил попробовать следующее решение:

Предлагаю запустить увеличение этого счётчика, от 0 до нужной конечной цифры, последовательно +1… +1.. +1…

Работает так: 
- начинает увеличиваться не дожидаясь загрузки самой цифры
- в момент загрузки у скрипта появляется число и появляется понимание до какого числа крутиться.
- настроить скорость +1+1 таким образом, чтобы “уж точно успело догрузиться"

Получится так сделать??

**Comment by priezz** [comment]
Попробуем
16 дек. 2015 г. 21:12 пользователь "TatyanaSkorochkina" <
notifications@github.com> написал:
