### ISSUE TITLE
Поп-ап (горизонтальный скролл)

### ISSUE THREAD

**Issue by TatyanaSkorochkina** [infographer/ironviz#33]
--Отсутствует горизонтальный скролл в поп-апах--

Update:
периодически появляются ненужные скроллы в Chrome.
См скриншот
https://www.dropbox.com/s/f6omjum0m9r20ub/%D0%A1%D0%BA%D1%80%D0%B8%D0%BD%D1%88%D0%BE%D1%82%202015-12-03%2018.11.32.png?dl=0

**Comment by jajapr** [comment]
Прошу пояснить, о чем речь. Приложите макет или скриншот, пожалуйста.

**Comment by TatyanaSkorochkina** [comment]
@jajapr Майя, я напутала - проблема не в том, что их нет, а в том, что периодически появляются ненужные скроллы в Chrome. 
См скриншот
https://www.dropbox.com/s/f6omjum0m9r20ub/%D0%A1%D0%BA%D1%80%D0%B8%D0%BD%D1%88%D0%BE%D1%82%202015-12-03%2018.11.32.png?dl=0

**Comment by priezz** [comment]
Нам не удается воспроизвести проблему

**Comment by TatyanaSkorochkina** [comment]
@priezz Александр, а с чем это в принципе может быть связано?

**Comment by priezz** [comment]
Все веб-браузеры (причем речь о сочетании четырех параметров "ОС-версия ОС-браузер-версия браузера", к которым добавляется еще разрешение экрана, плотность пикселей и размеры окна) отображают страницы по-разному. Плюс иногда настройки скроллбаров наследуются от настроек ОС (отображать только при скролле, показывать всегда и т.п.). Вам "повезло" попасть на отличный от ожидаемого результат. Какие версии windows и chrome на ПК, где так выглядит?

**Comment by TatyanaSkorochkina** [comment]
Ждём ответа от Олега, так как эта проблема возникла только у него...

**Comment by TatyanaSkorochkina** [comment]
Проблема исчезла
