### ISSUE TITLE
Дизайн (инфоблоки)

### ISSUE THREAD

**Issue by TatyanaSkorochkina** [infographer/ironviz#34]
Реализация не соответствует дизайну

**Comment by TatyanaSkorochkina** [comment]
![2015-10-28 13-24-53 002_portrait_h1 png](https://cloud.githubusercontent.com/assets/15325322/10785704/de45ed5e-7d76-11e5-94c6-c90c34ac2ddb.png)

**Comment by priezz** [comment]
Сделано, но без клика, т.к. событие "click" подразумевает, что кнопка нажата и отпущена, а у нас при этом сразу же открывается правая панель, которая закрывает баббл. Реагировать на нажатую, но не отпущенную кнопку возможности нет. Да и на планшетах это не будет работать.
