### ISSUE TITLE
Дизайн (карта) - выбор конкретного года

### ISSUE THREAD

**Issue by TatyanaSkorochkina** [infographer/ironviz#36]
На карте не реализован выбор конкретного года старта при включенной вкладке "Все года",

**Comment by TatyanaSkorochkina** [comment]
1. выбор конкретного года старта при включенной вкладке "Все годы" - прошу пояснить, что имеется ввиду?

**Comment by TatyanaSkorochkina** [comment]
Ждём ответа от Олега

**Comment by TatyanaSkorochkina** [comment]
![22](https://cloud.githubusercontent.com/assets/15325322/11962636/52faf170-a8f2-11e5-91a7-14e388145ded.png)

**Comment by priezz** [comment]
Такой макет мы ранее не видели. Просьба расписать, как это должно работать.

**Comment by TatyanaSkorochkina** [comment]
Готовим описание логики

**Comment by TatyanaSkorochkina** [comment]
@priezz Александр, идея была следующая:
Сейчас, если пользователь нажимает на какой-то город (старт), то ему открывается список всех триатлетов, которые прошли эту дистанцию. Если соревнование там проходило всего 1 раз - то всё ОК. А вот если там несколько раз проходили старты, то список смотреть уже не так удобно и понятно с учётом того, что там нет параметра "Год".
Вот для решения этой ситуации и был придуман дополнительный фильтр по годам уже на самом старте. Т.е. если изначально пользователь установил глобальный фильтр "Все года" и хочет посмотреть какой-то старт, где соревнования проходили несколько раз, то при наведении мыши на эту точку всплывает экран с возможностью выбора конкретного года именно для этого старта и соответственно после этого открывается уже отфильтрованный список триатлетов, проходивших дистанцию в конкретный год.
https://www.dropbox.com/s/txomp8nxjhccp8e/%D0%A1%D0%BA%D1%80%D0%B8%D0%BD%D1%88%D0%BE%D1%82%202015-12-25%2012.27.32.png?dl=0

Если выбран конкретный год в глобальном фильтре, то такая возможность должна отсутствовать.

Комментарий от Олега:
"Я сделал этот фильтр еще на этапе разработки дизайна, думал, что будут сложности при просмотре данных за все годы без этого фильтра. Но так как за прошедшее время никаких замечаний по этому поводу не было, я уже не уверен, что его вообще нужно реализовывать."

Если это сделать быстро и несложно - давайте сделаем; если нет - то отложим на будущее...

**Comment by priezz** [comment]
>  А вот если там несколько раз проходили старты, то список смотреть уже не так удобно и понятно с учётом того, что там нет параметра "Год".

Список выводится только за тот год, который выбран в текущий момент (что и отражено в заголовке таблицы), либо за все годы, если в фильтре выбраны "Все годы". 

Всплывающий фильтр, действительно, может вызвать сложности, а кроме того может начать сбивать пользователя с толку. Предлагаем не делать фильтр вообще. А вот в таблице можно было бы год указать (в версии >1.0).
