### ISSUE TITLE
Результаты_Анализ по возрастам - диаграмма некорректно реагирует при наведение курсора

### ISSUE THREAD

**Issue by TatyanaSkorochkina** [infographer/ironviz#38]
Если в разделе Результаты_Анализ по возрастам выбрать в фильтре "Ж", то столбик для времени "15:30", где 1 значение, не реагирует на наведение курсора (попап с доп информацией не отображается). 

![2015-12-15 15-02-52 tri infographer ru analysis age](https://cloud.githubusercontent.com/assets/15325322/11810056/67c889ac-a33c-11e5-909f-5e8713944401.png)

Для всех остальных ситуаций, где 1 значение - всё ОК. Например:
![2015-12-15 15-03-49 tri infographer ru analysis age](https://cloud.githubusercontent.com/assets/15325322/11810083/91970718-a33c-11e5-982e-3a6aaa7d00c1.png)

**Comment by priezz** [comment]
@TatyanaSkorochkina огромная просьба коротко излагать суть прямо в названии (и если совсем не лень, переименуйте уже существующие задачи). Также указывайте либо полное название страницы/диаграммы, либо приводите полный путь до страницы, либо прикрепляйте скриншот. Иначе приходится догадываться, а догадки не всегда оказываются верны.
Также если ссылаетесь на др задачи, можно ставить знак # перед номером, тогда будет формироваться именно ссылка и задачу не придется искать руками/глазами.

О какой именно диаграмме тут речь?

**Comment by priezz** [comment]
Конечно, попасть курсором в полоску толщиной около 1 пикселя очень сложно... Но иногда получается, см мой скриншот.
На втором вашем скриншоте это сделать проще, т.к. полоска толще из-за отсутствия серого наслоения выше. Думаю, это не стоит это считать ни багом, ни вообще проблемой.

![15-30](https://cloud.githubusercontent.com/assets/6680317/11811975/368a0fc6-a339-11e5-86f7-2487ffceab10.png)
