### ISSUE TITLE
Ссылки на сайты

### ISSUE THREAD

**Issue by TatyanaSkorochkina** [infographer/ironviz#4]
Лого Трилайфа и Инфографера сделать активными ссылками на сайты

**Comment by jajapr** [comment]
Татьяна,  прошу предоставить точный ссылки.

**Comment by TatyanaSkorochkina** [comment]
http://agency.infographer.ru/
http://www.trilife.ru/

**Comment by TatyanaSkorochkina** [comment]
ОК
