### ISSUE TITLE
Результаты_Анализ по возрастам - добавить в фильтр 3 возрастные группы

### ISSUE THREAD

**Issue by TatyanaSkorochkina** [infographer/ironviz#40]
Аналогично #35 в разделе Результаты_Анализ по возрастам добавить в фильтр по возрастным группам значения: 70-74; 75-79 и 80+

**Comment by priezz** [comment]
Добавить фильтр совсем не сложно, но сейчас строка с фильтрами впритык влезает в экран iPad. При добавлении еще трех фильтров, это будет уже две строки - совсем не красиво. Стоит ли это делать, понимая, что ни одного результата в этих группах нет?

Вообще в мире есть хоть один триатлонист старше 75, старше 80?

**Comment by TatyanaSkorochkina** [comment]
@priezz в мире такие результаты есть, поэтому мы собственно и решили расширить область возрастных групп на будущее... По реализации сейчас подумаем...

**Comment by TatyanaSkorochkina** [comment]
Корректируем исходный макет...

**Comment by TatyanaSkorochkina** [comment]
@priezz Скорректировали размер кнопок на макете (на всё остальное, в частности на временную шкалу, внимания не обращайте - макет просто старый ))
![004_scores](https://cloud.githubusercontent.com/assets/15325322/11869869/049cb314-a4d4-11e5-899e-b260b1a2da60.png)

Исходник можно найти по ссылке: https://www.dropbox.com/s/1u8yvumxcz9u97u/004_Scores.ai?dl=0
