### ISSUE TITLE
Результаты_Распределение по возрастам - отражение попапа со средним значением некорректно реагирует на положение курсора

### ISSUE THREAD

**Issue by TatyanaSkorochkina** [infographer/ironviz#42]

**Comment by TatyanaSkorochkina** [comment]
![2015-12-13 01-14-26 tri infographer ru distribiution age](https://cloud.githubusercontent.com/assets/15325322/11809432/e67577e2-a337-11e5-8744-7603028f5511.png)
![2015-12-13 01-17-28 tri infographer ru distribiution age](https://cloud.githubusercontent.com/assets/15325322/11809431/e67218d6-a337-11e5-8187-4060cabda2f0.png)

"некорректно отображается поп-ап со средним временем для диапазонов 18-24; 30-34; 40-44 и 50-54" - не вполне ясно, в чем именно заключается некорректность. И как должно быть корректно.  Из скриншотов это не видно. Также не ясно, что именно обведено красным.

Продублирую здесь скрины и попробую пояснить:
на снимках показана ситуация для группы 18-24 (для других поведение аналогичное).
На 1-м снимке маркером обведено приблизительное положение курсора, которое инициирует отражение попапа со средним значением именно для этой группы.
На 2-м снимке показано, что курсор наведён на значок среднего времени для группы 18-24, тем не менее отражается попап для группы 25-29...

Для всех остальных диапазонов (25-29; 35-39;45-49 и далее) - всё корректно. Вот и для этих должно быть точно так же.

**Comment by priezz** [comment]
1-ый снимок - Вы так и не сформулировали, в чем некорректность. В том, что попап всплывает при нахождении курсора слишком далеко от иконки часов? При каких условия это вопрроизводится? Изменить поведение не получится, оно диктуется библиотекой AmCharts, но надо хотя бы понимать, когда это возникает. У меня так и не получилось получить что-то подобное.

2-ой снимок - По горизонтальной оси значения находятся очень близко друг от друга, а библиотека ориентируется в первую очередь на абсцисс-координату при отображении попапа. Видимо курсор был ближе к среднему в группе "25-29", чем к среднему в группе "20-24".

Если значения на шкале продолжают раздражать, то единственным решением может быть их выключение.

**Comment by TatyanaSkorochkina** [comment]
@priezz По 1-му снимку - да, проблема в том, что нужный попап всплывает, когда курсор мыши достаточно далеко от иконки часов (собственно курсор ровно там, где идёт вертикальная отсечка к оси времени). Не понятно, почему для одних диапазонов всё нормально, а для других возникает подобная проблема?

Проверяю на OS X версия 10.9.5 в браузере Google Chrome версия 47.0.2526.80 (64-bit)

По 2-му снимку - курсор был ровно в области "часов" для среднего значения 18-24. Тестировала эту ситуацию неоднократно, воспроизвести правильный результат так и не вышло...

**Comment by priezz** [comment]
Да, в такой комбинации воспроизвелось - дело было в пропорциях изображения часов (они не нравились библиотеке в хроме) - поправили.
