### ISSUE TITLE
Инфоблоки

### ISSUE THREAD

**Issue by TatyanaSkorochkina** [infographer/ironviz#6]
Доп. информация в баблах выезжает с того края экрана, к которому он примыкает вплотную

**Comment by jajapr** [comment]
На наш взгляд, это кроме раздражения пользователя, ничего не принесет. Большинство людей консервативны и ожидают увидеть аналогичную предыдущей информацию в том же месте, что и в прошлый раз.

**Comment by TatyanaSkorochkina** [comment]
@jajapr Хорошо, давайте оставим так, как есть.
